### ISSUE TITLE
Config/Plugin Locations

### ISSUE THREAD

**Issue by bbakermmc** [binhex/arch-rider#1]
Im confused as to where the location of the config/plugins etc are being stored.  I assumed in the /config folder that was defined in Unraid, but that doesnt seem to be the case?

I also see this:
![image](https://user-images.githubusercontent.com/30090055/50569313-20b78480-0d30-11e9-80a0-3cf3eba0397e.png)

**Comment by binhex** [comment]
This was a typo in the default path to the idea.properties file, its now been resolved, see commit here:-

https://github.com/binhex/arch-rider/commit/38cd10fff889c61eaa57154d08e9b8b5e6776f48#diff-f6e15f3f229e016f3ca4ab220ce7fb37

please pull down latest image, this will then save config, system, plugins and logs in /config
