### ISSUE TITLE
.Net Core CLI 

### ISSUE THREAD

**Issue by bbakermmc** [binhex/arch-rider#2]
This probably needs added via the base image :)

Should probably expose a port too so we can configure the .net web projects to use that port.

![image](https://user-images.githubusercontent.com/30090055/50569409-22824780-0d32-11e9-82d3-64ea7b82967e.png)

**Comment by binhex** [comment]
.net core or .net sdk?

**Comment by binhex** [comment]
i spotted in rider it references .net core sdk so ive now included this, image is currently building. please keep in mind it looks like the auto detection stuff built into rider is currently broke so please do the following:-

https://stackoverflow.com/questions/48739309/rider-cannot-detect-net-core-installation-on-ubuntu

**Comment by bbakermmc** [comment]
Thanks.  Yeah it would of been the dot net core sdk :)

Sent from my iPhone

On Jan 2, 2019, at 8:36 AM, binhex <notifications@github.com<mailto:notifications@github.com>> wrote:


i spotted in rider it references .net core sdk so ive now included this, image is currently building. please keep in mind it looks like the auto detection stuff built into rider is currently broke so please do the following:-

https://stackoverflow.com/questions/48739309/rider-cannot-detect-net-core-installation-on-ubuntu
