### ISSUE TITLE
RIDER_VM_OPTIONS

### ISSUE THREAD

**Issue by bbakermmc** [binhex/arch-rider#3]
Can you add this to the install.sh also.  It looks like I can pass the option to override RIDER_PROPERTIES and RIDER_VM_OPTIONS that way we can override the default values if we need too, but also its not "standard" as to cause you issues.

export RIDER_VM_OPTIONS=$(echo "${RIDER_VM_OPTIONS}" | sed -e 's~^[ \t]*~~;s~[ \t]*$~~')
if [[ ! -z "${RIDER_VM_OPTIONS}" ]]; then
	echo "[info] RIDER_VM_OPTIONS defined as '${RIDER_VM_OPTIONS}'" | ts '%Y-%m-%d %H:%M:%.S'
fi

**Comment by binhex** [comment]
done, image is building
